---
- name: Deploy Infra Components for DevOps with OpenShift and OpenShift Ansible Broker Workshop
  hosts: localhost
  gather_facts: false
  run_once: true
  vars:
    openshift_cli: oc
    digitalocean_api_key: 
  tasks:
    - include_role:
        name: openshift_common_facts
      vars:
        set_hostname_suffix: false
      tags: always

    - name: check to be logged in as cluster admin
      shell: "{{ openshift_cli }} get project default"
      changed_when: false

    # configure ansible broker
    - name: create digital ocean secret
      shell: |
        {{ openshift_cli }} delete secret digital-ocean-api-key -n openshift-ansible-service-broker
        {{ openshift_cli }} create secret generic digital-ocean-api-key --from-literal=api_key={{ digitalocean_api_key }} -n openshift-ansible-service-broker
      ignore_errors: true
      tags: broker

    - name: update ansible broker config
      shell: |
        {{ openshift_cli }} delete configmap broker-config -n openshift-ansible-service-broker
        {{ openshift_cli }} create configmap broker-config --from-file=broker-config=files/broker-config-prod.yml -n openshift-ansible-service-broker
      tags: broker

    - name: restart ansible broker
      shell: |
        {{ openshift_cli }} rollout latest dc/asb -n openshift-ansible-service-broker
        {{ openshift_cli }} delete pod -l webconsole=true -n openshift-web-console
      tags: broker